{
 "title": "Kubi",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Currently Active Token",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(kubi_valid_token_total{status=\"token_success\"}[4h]))"
    }
   ]
  },
  {
   "title": "Projects",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (name) (kubi_project_creation))"
    }
   ]
  },
  {
   "title": "Managed Namespaces",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (name) (kubi_namespace_creation))"
    }
   ]
  },
  {
   "title": "Managed RoleBindings",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (name, target_namespace) (kubi_rolebindings_creation))"
    }
   ]
  },
  {
   "title": "Managed Service Account",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (name, target_namespace) (kubi_service_account_creation))"
    }
   ]
  },
  {
   "title": "Managed Network Policy",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (name, target_namespace) (kubi_network_policy_creation))"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Request per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kubi_http_requests_count{path!=\"/metrics\"}[1m])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  { "title": "Token", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Valid Token",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kubi_valid_token_total{status=\"token_success\"}[4h]))",
     "legendFormat": "token"
    }
   ]
  },
  { "title": "Resource Generation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Project Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kubi_project_creation{status=\"error\"}[30m])",
     "legendFormat": "error - {{ name }}"
    },
    {
     "expr": "increase(kubi_project_creation{status=\"created\"}[30m])",
     "legendFormat": "created - {{ name }}"
    },
    {
     "expr": "increase(kubi_project_creation{status=\"updated\"}[30m])",
     "legendFormat": "updated - {{ name }}"
    }
   ]
  },
  {
   "title": "Namespace Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kubi_namespace_creation{status=\"error\"}[20m])",
     "legendFormat": "error - {{ name }}"
    },
    {
     "expr": "increase(kubi_namespace_creation{status=\"created\"}[20m])",
     "legendFormat": "created - {{ name }}"
    },
    {
     "expr": "increase(kubi_namespace_creation{status=\"updated\"}[30m])",
     "legendFormat": "updated - {{ name }}"
    },
    {
     "expr": "increase(kubi_namespace_creation{status=\"ok\"}[30m])",
     "legendFormat": "ok - {{ name }}"
    }
   ]
  },
  {
   "title": "Rolebindings Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kubi_rolebindings_creation{status=\"error\"}[30m])",
     "legendFormat": "error {{ target_namespace }} - {{ name }}"
    },
    {
     "expr": "increase(kubi_rolebindings_creation{status=\"created\"}[30m])",
     "legendFormat": "created {{ target_namespace }} - {{ name }}"
    },
    {
     "expr": "increase(kubi_rolebindings_creation{status=\"updated\"}[30m])",
     "legendFormat": "updated {{ target_namespace }} - {{ name }}"
    }
   ]
  },
  {
   "title": "Service Account Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kubi_service_account_creation{status=\"error\"}[20m])",
     "legendFormat": "error  {{ target_namespace }} {{ name }}"
    },
    {
     "expr": "increase(kubi_service_account_creation{status=\"created\"}[20m])",
     "legendFormat": "created  {{ target_namespace }} - {{ name }}"
    },
    {
     "expr": "increase(kubi_service_account_creation{status=\"updated\"}[30m])",
     "legendFormat": "updated  {{ target_namespace }} - {{ name }}"
    },
    {
     "expr": "increase(kubi_service_account_creation{status=\"ok\"}[30m])",
     "legendFormat": "ok  {{ target_namespace }} - {{ name }}"
    }
   ]
  },
  {
   "title": "Network Policy Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kubi_network_policy_creation{status=\"error\"}[30m])",
     "legendFormat": "error {{ target_namespace }} - {{ name }}"
    },
    {
     "expr": "increase(kubi_network_policy_creation{status=\"created\"}[30m])",
     "legendFormat": "created {{ target_namespace }} - {{ name }}"
    },
    {
     "expr": "increase(kubi_network_policy_creation{status=\"updated\"}[30m])",
     "legendFormat": "updated {{ target_namespace }} - {{ name }}"
    }
   ]
  }
 ]
}