---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpldapadmin
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpldapadmin
  template:
    metadata:
      labels:
        app: phpldapadmin
    spec:
      containers:
      - name: phpldapadmin
        image: osixia/phpldapadmin:0.9.0
        env:
        - name: PHPLDAPADMIN_LDAP_HOSTS
          value: kube-ldap
        - name: PHPLDAPADMIN_HTTPS
          value: "false"
        - name: PHPLDAPADMIN_LDAP_PORT
          value: "389"
        ports:
        - containerPort: 80
---
apiVersion : v1
kind : Service
metadata :
  name : phpldapadmin-service
  namespace: kube-system
spec:
  type: NodePort
  ports :
    - port : 9943
      targetPort: 80
  selector :
    app : phpldapadmin:
