#!/bin/zsh

export CUSTOM_LABELS="quota=managed"
export DEFAULT_PERMISSION="pod-reader"
export LDAP_ADMIN_GROUPBASE="cn=DL_ADMIN_TEAM,OU=GLOBAL,ou=Groups,dc=kubi,dc=ca-gip,dc=github,dc=com"
export LDAP_ADMIN_USERBASE="dc=kubi,dc=ca-gip,dc=github,dc=com"
export LDAP_BINDDN="cn=admin,dc=kubi,dc=ca-gip,dc=github,dc=com"
export LDAP_GROUPBASE="ou=LOCAL,ou=Groups,dc=kubi,dc=ca-gip,dc=github,dc=com"
export LDAP_PORT="389"
export LDAP_SERVER="kube-ldap.kube-system.svc.cluster.local"
export LDAP_USE_SSL="false"
export LDAP_USERBASE="ou=People,dc=kubi,dc=ca-gip,dc=github,dc=com"
export LDAP_USERFILTER="(cn=%s)"
export LOCATOR="local"
export PUBLIC_APISERVER_URL="https://api.devops.managed.vm"
export TENANT="cagip"
export KUBERNETES_SERVICE_HOST="kubernetes.docker.internal"
export KUBERNETES_SERVICE_PORT="6443"
export LDAP_PASSWD="password"